In [17]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [18]:
# # Load the data
# train_data = pd.read_csv('/Users/geraldzhao/Desktop/ML_final_proj/train.csv')
# test_data = pd.read_csv('/Users/geraldzhao/Desktop/ML_final_proj/test.csv')

In [19]:
# Load the data
data = pd.read_csv('/Users/geraldzhao/Desktop/ML_final_proj/train.csv')
X = data.drop('Transported', axis=1)
y = data['Transported']

In [20]:
# Define categorical and numerical columns
categorical_cols = [col for col in X.columns if X[col].dtype == 'object']
numerical_cols = [col for col in X.columns if X[col].dtype in ['int64', 'float64']]

# Preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler())]), numerical_cols),
        ('cat', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', OneHotEncoder(handle_unknown='ignore'))]), categorical_cols)
    ])

# Prepare data by applying preprocessing
X_processed = preprocessor.fit_transform(X)
X_train, X_val, y_train, y_val = train_test_split(X_processed, y, test_size=0.2, random_state=42)

In [21]:
# Define parameter grid
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}

# List to store results
results = []

In [22]:
# Iterate over each combination of parameters
for n_estimators in param_grid['n_estimators']:
    for max_depth in param_grid['max_depth']:
        for min_samples_split in param_grid['min_samples_split']:
            for min_samples_leaf in param_grid['min_samples_leaf']:
                for max_features in param_grid['max_features']:
                    # Setup the Random Forest classifier
                    rf = RandomForestClassifier(
                        n_estimators=n_estimators,
                        max_depth=max_depth,
                        min_samples_split=min_samples_split,
                        min_samples_leaf=min_samples_leaf,
                        max_features=max_features,
                        random_state=42
                    )
                    rf.fit(X_train, y_train)

                    # Predict on training and validation set
                    y_train_pred = rf.predict(X_train)
                    y_val_pred = rf.predict(X_val)

                    # Calculate metrics
                    train_accuracy = accuracy_score(y_train, y_train_pred)
                    val_accuracy = accuracy_score(y_val, y_val_pred)
                    precision = precision_score(y_val, y_val_pred, average='macro', zero_division=0)
                    recall = recall_score(y_val, y_val_pred, average='macro', zero_division=0)

                    # Store results
                    results.append({
                        'n_estimators': n_estimators,
                        'max_depth': max_depth,
                        'min_samples_split': min_samples_split,
                        'min_samples_leaf': min_samples_leaf,
                        'max_features': max_features,
                        'Training Accuracy': train_accuracy,
                        'Validation Accuracy': val_accuracy,
                        'Precision': precision,
                        'Recall': recall
                    })

In [27]:
# Convert results to DataFrame for display
results_df = pd.DataFrame(results)
results_df.to_csv('rand_forest_result_table.csv', index=False)
results_df

,n_estimators,max_depth,min_samples_split,min_samples_leaf,max_features,Training Accuracy,Validation Accuracy,Precision,Recall
0,100,10.0,2,1,sqrt,0.738712,0.740656,0.744631,0.741255
1,100,10.0,2,1,log2,0.746045,0.729155,0.730289,0.729472
2,100,10.0,2,2,sqrt,0.740581,0.744681,0.747681,0.745196
3,100,10.0,2,2,log2,0.504745,0.505463,0.752589,0.500581
4,100,10.0,5,1,sqrt,0.740006,0.741231,0.745437,0.741847
5,100,10.0,5,1,log2,0.746045,0.729155,0.730289,0.729472
6,100,10.0,5,2,sqrt,0.740437,0.744681,0.747681,0.745196
7,100,10.0,5,2,log2,0.504458,0.505463,0.752589,0.500581
8,100,20.0,2,1,sqrt,0.740581,0.741806,0.745946,0.742416
9,100,20.0,2,1,log2,0.774231,0.728580,0.729828,0.728914
10,100,20.0,2,2,sqrt,0.738280,0.742381,0.746604,0.742997
11,100,20.0,2,2,log2,0.504745,0.505463,0.752589,0.500581
12,100,20.0,5,1,sqrt,0.739574,0.740656,0.744929,0.741277
13,100,20.0,5,1,log2,0.773512,0.728005,0.729290,0.728344
14,100,20.0,5,2,sqrt,0.737274,0.741806,0.746096,0.742427
15,100,20.0,5,2,log2,0.504458,0.505463,0.752589,0.500581
16,100,NaN,2,1,sqrt,1.000000,0.781484,0.781777,0.781631
17,100,NaN,2,1,log2,1.000000,0.785509,0.786153,0.785730
18,100,NaN,2,2,sqrt,0.738280,0.741806,0.746096,0.742427
19,100,NaN,2,2,log2,0.504745,0.505463,0.752589,0.500581
20,100,NaN,5,1,sqrt,0.999856,0.778033,0.778324,0.778181
21,100,NaN,5,1,log2,1.000000,0.784934,0.785229,0.785082
22,100,NaN,5,2,sqrt,0.737849,0.741231,0.745437,0.741847
23,100,NaN,5,2,log2,0.504458,0.505463,0.752589,0.500581
24,200,10.0,2,1,sqrt,0.740725,0.743531,0.747474,0.744125
25,200,10.0,2,1,log2,0.767472,0.742381,0.742778,0.742558
26,200,10.0,2,2,sqrt,0.739862,0.745256,0.748864,0.745822
27,200,10.0,2,2,log2,0.504602,0.505463,0.752589,0.500581
28,200,10.0,5,1,sqrt,0.741300,0.742381,0.746455,0.742986
29,200,10.0,5,1,log2,0.767472,0.742381,0.742778,0.742558
30,200,10.0,5,2,sqrt,0.739862,0.745256,0.748864,0.745822
31,200,10.0,5,2,log2,0.504314,0.505463,0.752589,0.500581
32,200,20.0,2,1,sqrt,0.743745,0.747556,0.752414,0.748212
33,200,20.0,2,1,log2,0.781565,0.737205,0.737198,0.737220
34,200,20.0,2,2,sqrt,0.738999,0.745256,0.749446,0.745867
35,200,20.0,2,2,log2,0.504602,0.505463,0.752589,0.500581
36,200,20.0,5,1,sqrt,0.742738,0.746406,0.751409,0.747073
37,200,20.0,5,1,log2,0.781133,0.736630,0.736618,0.736639
38,200,20.0,5,2,sqrt,0.739287,0.745256,0.749446,0.745867
39,200,20.0,5,2,log2,0.504314,0.505463,0.752589,0.500581
40,200,NaN,2,1,sqrt,1.000000,0.786084,0.786474,0.786255
41,200,NaN,2,1,log2,1.000000,0.785509,0.786032,0.785708
42,200,NaN,2,2,sqrt,0.739143,0.746406,0.750315,0.746995
43,200,NaN,2,2,log2,0.504602,0.505463,0.752589,0.500581
44,200,NaN,5,1,sqrt,1.000000,0.783209,0.783482,0.783351
45,200,NaN,5,1,log2,1.000000,0.786084,0.786474,0.786255
46,200,NaN,5,2,sqrt,0.738424,0.744681,0.748788,0.745286
47,200,NaN,5,2,log2,0.504314,0.505463,0.752589,0.500581